name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build and Push To Docker Hub
        run: |
          docker build . --file Dockerfile --tag wiseoldman/metrics:latest
          docker push wiseoldman/metrics:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker compose pull metrics
            docker compose up -d --no-deps --build metrics
